var GAME_LEVELS = [
  ["                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                        o                                                                                                                           ",
   "                                                                                                                          oo                                                        ",
   "                                                                                oo                                                                                                  ",
   "              oo                                  xxxx  ^  xxxx                                                                                                                     ",
   "                                                  xxxx!!!!!xxxx                xxxx                                      xxxx                                                       ",
   "             xxxx                            xxxxxxx!!!!!!!!!xxxxxxx                                                                                                                ",
   "                                             xxxxxxx!!!!!!!!!xxxxxxx                            oo              xxxx              xxxx                                              ",
   "    xxxx              xxxx              xxxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxx                                                                                                           ",
   "                                        xxxxxxx!!!!!!!!!!!!!!!!!!!xxxxxxx                      xxxx                                          xxxxxx           xx                   x",
   "                                   xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx                                                               xxxxxx>       o        o             <x",
   "    @                              xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx                         xxxxx        ^           ^            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx  ^   ^   xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx   ^  ^   xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  ],

  ["                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                       xxxx                         ",
   "                                                                                                                                               o                                    ",
   "                                                                                                                                             xxxx                                   ",
   "                                     xxxxx                                                                                                                      xxxx                ",
   "                                               xxxx                                             o      xxxx     xxxx                    xxxx                                        ",
   " @       xxxxx             xxxxx               xxxx           o             xxxx              xxxx                                                                                  ",
   "xxxx                o                          xxxx                         xxxx                                                 xxxxxxxxxxxxxxxxx                         o        ",
   "xxxx              xxxxx                        xxxxxxxxxxxxx     xxxxxxxxxxxxxxx     xxxx                                        xxxxxxxxxxxxxxxxx                       xxxx       ",
   "xxxx                                           xxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                xxxx       ",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           ",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  ],

  ["                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                                    ",
   "                                                                                                                                                                   xxxxxx           ",
   "             @                         xxxx                                                       o                                                                                 ",
   "            xxxx                                                   o                                                                                       xxxx                     ",
   "                              xxxx                                                          xxxx     xxxx                                                                           ",
   "                                                xxxx               o                                                                              xxxx                              ",
   "   xxxx      o       xxxx                                         xxx              xxxx                                                                                             ",
   "                                                                                                              xxxx     xxxx     xxxx     xxxx                                       ",
   "                                                         xxxx             xxxx                                                                                                 o    ",
   "            xxxx                                                                                                                                                               x    ",
   "                                                                                                                                                                                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  ]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
